"""M2 data platform: assets, market data, economic indicators, ingestion runs

Hand-written rather than autogenerated, per the Phase 1 plan's decision 3 and the
lesson recorded in its verification log: the autogenerated M1 revision shipped two
defects — an unimported application symbol and a downgrade that left native enum
types behind, so downgrade-then-upgrade failed.

Both hazards recur here. Four new enum types are created, and all four are dropped
explicitly in `downgrade`; SQLAlchemy's `Enum` creates a Postgres type as a side
effect of `create_table` but drops nothing on `drop_table`.

Revision ID: c3914c27454e
Revises: db5cc163799f
Create Date: 2026-08-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c3914c27454e"
down_revision: str | None = "db5cc163799f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_TYPES = ("asset_type", "asset_class", "economic_series", "ingestion_status")

# Values are duplicated from app.models.enums on purpose. A migration that imports
# application code breaks the moment that code changes, because an old revision must
# keep describing the schema as it was when it was written.
ASSET_TYPE = sa.Enum("EQUITY", "ETF", "BOND", "COMMODITY", "INDEX", name="asset_type")
ASSET_CLASS = sa.Enum("EQUITY", "BOND", "COMMODITY", "REAL_ESTATE", "CASH", name="asset_class")
ECONOMIC_SERIES = sa.Enum(
    "INFLATION", "INTEREST_RATE", "GDP", "UNEMPLOYMENT", "FX_RATE", name="economic_series"
)
INGESTION_STATUS = sa.Enum("RUNNING", "SUCCESS", "PARTIAL", "FAILED", name="ingestion_status")

PRICE = sa.Numeric(18, 6)


def upgrade() -> None:
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("asset_type", ASSET_TYPE, nullable=False),
        sa.Column("asset_class", ASSET_CLASS, nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD"),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # A unique index rather than a separate UNIQUE constraint, because that is what
    # `mapped_column(unique=True, index=True)` renders — and a schema that does not
    # match the models makes every future autogenerate diff untrustworthy.
    op.create_index("ix_assets_symbol", "assets", ["symbol"], unique=True)
    op.create_index("ix_assets_asset_class", "assets", ["asset_class"])
    op.create_index("ix_assets_is_active", "assets", ["is_active"])

    op.create_table(
        "market_data",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", PRICE, nullable=False),
        sa.Column("high", PRICE, nullable=False),
        sa.Column("low", PRICE, nullable=False),
        sa.Column("close", PRICE, nullable=False),
        sa.Column("adj_close", PRICE, nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # FR-06's "zero duplicate (asset_id, date) rows", enforced by the database
        # rather than by the pipeline remembering to. Also the ON CONFLICT target
        # that makes ingestion idempotent.
        sa.UniqueConstraint("asset_id", "date", name="uq_market_data_asset_date"),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0 AND adj_close > 0",
            name="ck_market_data_prices_positive",
        ),
        sa.CheckConstraint("high >= low", name="ck_market_data_high_ge_low"),
        sa.CheckConstraint("volume >= 0", name="ck_market_data_volume_non_negative"),
    )
    op.create_index("ix_market_data_asset_id", "market_data", ["asset_id"])
    op.create_index("ix_market_data_date", "market_data", ["date"])
    # The access pattern for both the API (newest bars for one symbol) and M3's
    # feature windows. Without it every chart request is a sort.
    op.create_index(
        "ix_market_data_asset_date_desc",
        "market_data",
        ["asset_id", sa.text("date DESC")],
    )

    op.create_table(
        "economic_indicators",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("series", ECONOMIC_SERIES, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(18, 6), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        # FRED revises published figures; this is what makes a revision overwrite
        # in place instead of accumulating a second row for one as-of date.
        sa.UniqueConstraint("series", "date", name="uq_economic_indicator_series_date"),
    )
    op.create_index("ix_economic_indicators_series", "economic_indicators", ["series"])
    op.create_index("ix_economic_indicators_date", "economic_indicators", ["date"])

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("status", INGESTION_STATUS, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_written", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("symbols_ok", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("symbols_failed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ingestion_runs_job", "ingestion_runs", ["job"])
    op.create_index("ix_ingestion_runs_status", "ingestion_runs", ["status"])
    op.create_index("ix_ingestion_runs_correlation_id", "ingestion_runs", ["correlation_id"])
    # What /health queries: the newest run for a job, and the newest successful one.
    op.create_index(
        "ix_ingestion_runs_job_started_desc",
        "ingestion_runs",
        ["job", sa.text("started_at DESC")],
    )


def downgrade() -> None:
    op.drop_table("ingestion_runs")
    op.drop_table("economic_indicators")
    op.drop_table("market_data")
    op.drop_table("assets")

    # Dropping a table does not drop the enum types it used. Leaving them behind is
    # what made the M1 revision fail on downgrade-then-upgrade with
    # "type already exists".
    for name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {name}")
