"""M1 foundation: users, financial profiles, refresh tokens

Two corrections were made to Alembic's autogenerated output:

1. It emitted `app.core.crypto.EncryptedNumeric()` without importing `app`, which
   raises NameError on upgrade. Migrations should not import application code
   anyway — that code changes underneath old revisions. The encrypted columns are
   `Text` at the database level, so `sa.Text()` is both correct and stable.
2. Its downgrade dropped the tables but left the four native enum types in place,
   so a downgrade followed by an upgrade failed with "type already exists".

Revision ID: db5cc163799f
Revises:
Create Date: 2026-08-28
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "db5cc163799f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_TYPES = (
    "risk_appetite",
    "investment_goal",
    "investment_experience",
    "financial_literacy",
)


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        # §17.1 — terms accepted at registration. Not in PRD §12; see the Phase 1 plan.
        sa.Column("tos_accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "financial_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        # Encrypted at the application layer (Phase 1 decision 01). Ciphertext is
        # text on disk, so these columns are not queryable or aggregatable in SQL.
        sa.Column("income", sa.Text(), nullable=False),
        sa.Column("savings", sa.Text(), nullable=False),
        sa.Column(
            "risk_appetite",
            sa.Enum("CONSERVATIVE", "MODERATE", "AGGRESSIVE", name="risk_appetite"),
            nullable=False,
        ),
        sa.Column(
            "investment_goal",
            sa.Enum("RETIREMENT", "GROWTH", "WEALTH_CREATION", name="investment_goal"),
            nullable=False,
        ),
        sa.Column("investment_horizon", sa.Integer(), nullable=False),
        sa.Column(
            "experience",
            sa.Enum("NONE", "BEGINNER", "INTERMEDIATE", "ADVANCED", name="investment_experience"),
            nullable=False,
        ),
        sa.Column(
            "financial_literacy",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="financial_literacy"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Defence in depth: Pydantic rejects these first, but a bad write through
        # any other path is refused by the database too (FR-02).
        sa.CheckConstraint("age >= 18 AND age <= 120", name="ck_profile_age_range"),
        sa.CheckConstraint("investment_horizon >= 1", name="ck_profile_horizon_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_profiles_user_id"), "financial_profiles", ["user_id"], unique=True
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        # Groups tokens descended from one login, so reuse detection can revoke
        # the whole family (Phase 1 decision 02).
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.drop_index(op.f("ix_financial_profiles_user_id"), table_name="financial_profiles")
    op.drop_table("financial_profiles")

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    # Postgres enum types outlive the tables that used them; dropping the tables
    # alone leaves a downgrade-then-upgrade failing on "type already exists".
    for type_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
